import Head from "next/head";
import { useEffect, useLayoutEffect, useState } from "react";
import { Html5Qrcode, Html5QrcodeSupportedFormats } from "html5-qrcode";

let myState = true;

export default function Home() {
  useEffect(() => {
    const html5QrCode = new Html5Qrcode("reader", {
      formatsToSupport: [Html5QrcodeSupportedFormats.QR_CODE],
      verbose: true,
    });
    const qrCodeSuccessCallback = (decodedText: string) => {
      alert(decodedText);
    };
    const qrCodeErrorCallback = (decodedText: string) => {
      // alert(decodedText);
    };
    const config = { fps: 10, qrbox: { width: 250, height: 250 } };

    if (myState) {
      myState = false;
      html5QrCode.start(
        {
          facingMode:
            process.env.NODE_ENV === "development" ? "user" : "environment",
        },
        config,
        qrCodeSuccessCallback,
        qrCodeErrorCallback
      );
    }
  }, []);

  return (
    <>
      <Head>
        <title>Test Scan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="reader"></div>
      </main>
    </>
  );
}
